name: Build and Deploy

on: [push]

jobs:
  build-and-deploy:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
      brew install pandoc
      sh build.sh
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dst
